server:
  port: 4514
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://146.56.193.5:3306/ucsp
#    username: nanoic
#    password: t7S4HLhZ2HFh4P6j
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.mysql.cj.jdbc.MysqlDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

  data:
    redis:
      repositories:
        enabled: false

mybatis:
  mapper-locations: classpath*:/mapper/**
  type-aliases-package: com.gxyan.pojo

keys:
  SMSAccessID: 1
  SMSAccessSecret: 1

costume:
  upload:
    path: /home/ubuntu/Upload/

